### ISSUE TITLE
[1.12] Sophisticated Wolves: Dog treats and carrying cages don't work

### ISSUE THREAD

**Issue by SomeCascadianGuy** [satyrnidae/wolfarmor#95]
Issue Description
Whenever I try to give my dogs treats or put them in carrier cages in the Sophisticated Wolves mod, I can't do either of those.

Relevant mods:
Sophisticated Wolves

Reproduction Steps
1. Tame a wolf or spawn a sophisticated wolf.
2. Try to give the dog a treat or try to put it in a carrier cage by right clicking the dog while holding the item.

Screenshots / Videos
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61160242/80058574-7e9c4c80-84de-11ea-8bcd-c5911e035fb7.gif)

**Comment by CovertJaguar** [comment]
Can confirm. Log spams with the following when attempting to feed a Dog Treat to a vanilla Wolf:
```
[11:45:24] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
	at sophisticated_wolves.compatibility.CompatibilityWolfArmor.copyWolfItems(CompatibilityWolfArmor.java:66) ~[CompatibilityWolfArmor.class:?]
	at sophisticated_wolves.item.ItemDogTreat.func_111207_a(ItemDogTreat.java:52) ~[ItemDogTreat.class:?]
	at net.minecraft.item.ItemStack.func_111282_a(ItemStack.java:391) ~[aip.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1220) ~[aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by satyrnidae** [comment]
see https://github.com/NightKosh/Sophisticated-wolves/pull/90
